### PR TITLE
Fixed some compiler warnings

### PR DESCRIPTION
**Pull request by kamahen**
I tried compiling with g++ instead of gcc and there were a number of compiler warnings (one of which might have been a bug), so renamed a field and a few other small changes to remove the warnings. [The code won't be changed to C++]

### CODE REVIEW

**Comment by JanWielemaker** [comment]
Trying to understand this.  I see a rename from `pcre2_code` to `re_compiled`, which can't really fix anything, can it?
I see an added `const`.   If that is correct, fine.  There is AFAIK no semantic implication of `const` in C.    It merely documents the intend, gets a compiler error if you violate it and helps the compiler during optimization.   Did I miss something?

I'm ok applying this.    In general I do not welcome renaming variables except for being part of larger changes unless the name is really wrong.    In this case the new name is better, but the old one is not unacceptable. 

Such changes merely make the history harder to comprehend.

**Comment by kamahen** [comment]
C++ compiler seemed to be complaining about the field pcre2_code having the same name as the type pcre2_code (the error message was somewhat inscrutable). There's an additional complication here because `pcre2_code` actually expands to `pcre2_code_8` due to `PCRE_CODE_UNIT_WIDTH`, and there appeared to be a bug due to that at line 1163 (g++ complained; gcc was happy). So, changing the name seems safest - I agree with your general approach to not changing names because they confuse the history.

As for the `const char*` - g++ complained and there was a similar complaint in rocksdb4pl.cpp (which I've fixed in an upcoming PR).

**Comment by kamahen** [comment]
If you wish, I can revert the name change (and leave the other changes). However, my understanding is that C++ is more strict about some things than C is, especially with "undefined" or "implementation defined", and I prefer to turn on as many warnings as possible.

This is the error message (which I don't understand) that I got from g++ with line 130 `pcre2_code_8 *pcre2_code`:
```text
error: declaration of ‘pcre2_code_8* re_data::pcre2_code_8’ changes meaning of ‘pcre2_code_8’ [-fpermissive]
```

**Comment by JanWielemaker** [comment]
> If you wish, I can revert the name change (and leave the other changes).

No.  You motivated it well enough :smile:

**Pull request merged**
