### PR TITLE
Prepare existing PCRE1 code for migration to PCRE2

### PR DESCRIPTION
**Pull request by kamahen**
There are 2 commits: first one normalizes tabs, second one adds better validation to re_config/1
This is in preparation for Issue #2

### CODE REVIEW

**Comment by kamahen** [comment]
I've added a few more tests (UTF8) and clarified the behavior of re_config/1 with invalid terms.
I'm adding these tests to the PCRE1 version so that I have regression tests for when I've migrated everything to PCRE2 -- I expect to add more such tests as I complete more parts of the migration.

**Comment by kamahen** [comment]
I messed up the commits -- the last two should have been put together differently (one to fix optimize/optimise, one to fix the "uncleared exception", and one to simplify the calls to PL_..._error().

**Comment by kamahen** [comment]
I'm assuming that you'll do a squash on these commits. If you'd prefer, I can delete this PR and create a new squashed one.
I probably will continue making changes here -- I want to put as many changes as possible into the "base" pcre package so that the PCRE2 PR contains only changes needed for PCRE2.

**Comment by JanWielemaker** [comment]
Don't worry too much about the history.   There is some elegance in splitting into patches that already apply to the current version and a clean patch to move to pcre2.    It is probably not vital though.   Depends whether there are supported Linux distros that to not provide pcre2.

**Comment by kamahen** [comment]
I have a practical reason for keeping things split as much as possible between fixes to the existing (PCRE1) code and new code (PCRE2) -- bug-fixing. The more test cases I have, the easier it is to fix new bugs, especially as I don't finished enough of the conversion to be able to run much of the test suite.

For example, I recently discovered that `strchr()` was used instead of `strrchr()`. The fix belongs in this PR (together with its test cases), and I then merge it into my new code.

Also, it seems that there isn't a good migration guide for PCRE1->PCRE2 ... it's possible that I can point people to my changes as an example of a fairly comprehensive migration, and possibly also have the authors of PCRE2 verify that I've used the API properly. (There is one example migration code, but it doesn't use much of the API)

**Comment by kamahen** [comment]
I'm finding more bugs (and missing test cases) in the existing code, which is slowing down the work on migrating to PCRE2.
And we've just seen another bug report: Issue #5

**Comment by kamahen** [comment]
@JanWielemaker - I'm almost finished with the PCRE1 changes (e.g., adding Options to re_replace/5). When I've fixed the last issues, are you OK with merging this PR into the swipl-devel master? That'll give me a clean base for doing the PCRE2 migration.

The `fixme` items have -- as far as I know -- been unreported/untested bugs since before I started working on library(pcre).

**Comment by JanWielemaker** [comment]
I'm happy with merging.   Possibly the cache handling may need some revision, for example by using tabling to avoid most of the recomputations.   I'll have a closer look when you are done.

**Comment by kamahen** [comment]
Do you mean removing the assertz's for caching and instead using `table/1` directives? That would simplify the code a bit but probably not improve performance.
Anyway, if that's what you mean, I'd prefer doing it in a separate PR -- there's already too much in this PR.

**Comment by JanWielemaker** [comment]
When you think it is ready I'll study the result in more detail.   The compiled pattern caching is one one of my worries.  This was simple and fairly fast, but has become considerably more complicated.  I wonder about the performance impact.

**Comment by kamahen** [comment]
Hmmm ... for the caching, I didn't do much more than rename some predicates and change the arguments from Flags to Options. If that code worries you, I could remove it now and use `table` directives. Not sure how to measure the performance change (if any).
[But first I need to sort out the changes I've been making in parallel for PCRE2 -- my latest attempt to merge the master has ended in a git disaster.]

**Comment by JanWielemaker** [comment]
AFAIK in the old days there was a simple cache of pattern/flags to the regex.  Now we convert the flags to options, and cache from pattern/options to regex.   That is quite a bit more work.   If I looked at the code is does not distinguish compilation affecting options from others.   Not sure this should be done or not.   I'll surely want to know the performance impact isn't too big and if it is significant whether this can be improved.   Anyway, just tell me when you think it is time to do a final review.

**Comment by kamahen** [comment]
The old code only used the flags for cached compiled regexes; I changed the code to convert all the flags into options, merged  with the Options list, and then used the combined options list instead of the flags. The change to the assertz was trivial. (I added a few test cases to (hopefully) make it clear what wasn't working properly with the old code, and to verify that the new code does take into account all the compile time options.) I think that this caching can be easily changed to use tabling instead, with no significant performance problem.

[I'm guessing that the "original" pcre code had  the flags for controlling compilation plus a few options that were specific to the Prolog code; at some point more options that affected compilation were added (that couldn't be specified by flags), but the underlying cache code wasn't updated.]

**Comment by kamahen** [comment]
On second thoughts, tabling has the advantage of getting rid of some code that I modified and I'm not terribly happy about (I'm never happy with caches ...). 
So, I think I'll use tabling now rather than later.

Question: should I specify `:- table (re_compiled/3 compile_replacement/2) as shared`? (and rename these predicates to something more declarative). And redefine `re_flush/0` as:
```
re_flush :- abolish_module_tables(pcre).
```
(the documentation isn't clear on whether this would remove shared tabling)
Or should it be:
```
re_flush 👎 
    untable(re_compiled/3 as shared),
    untable(compile_replacement/2 as shared),
    table(re_compiled/3 as shared),
    table(compile_replacement/2 as shared)
```
Or something else?

**Comment by JanWielemaker** [comment]
There is one more option, which is to use goal_expansion/2 for the cases where the flags and options are given and translate them into some, preferably atomic, key that can be combined with the pattern to do the lookup as it used to be.

For re_flush, simple `abolish_module_tables(pcre).` is probably best.  The specific alternative is abolish_table_subgoals/1, certainly not untable and retable.   The dynamic ones exist for dealing with dynamic code as well as to experiment from the toplevel.

**Comment by kamahen** [comment]
@JanWielemaker  - *Finally* I think this is ready for review. There were a lot more changes than I had anticipated.

- It seems that the documentation is formatted (justified) at with `fill-column` 72. Is this correct?
  - When you confirm this, I'll submit a commit with the documentation justified using emacs `fill-paragraph 'justify`.
  - Is there an easy way to check that I've formatted the documentation properly (that is, display the generated HTML)?
    - (There seems to be a bug: if I un-comment `:-public '$re_portray'/2` I get the error `[TeX tokeniser: $re_portray/2:1: Unexpected end of file]` -- this seems to be due to the "$", so I can change the "$" to something else, if you wish. 
- If you wish me to squash the changes, I can do that, either by doing a `git push --force` or by creating a new PR that has a smaller set of commits.

PS: I've found `git difftool --tool=meld -y` to be handy for comparing changes because it has a variety of filters such as whether whitespace is significant or not.

**Comment by JanWielemaker** [comment]
Great!   Some answers:

  - Yes, formatting is by default done using justify with column 72.
  - To view the docs, simply build (assuming you did not disable building the docs).  Now the HTML is below the build dir in `packages/pcre/pcre.html` and you can see the plain text using `?- help(pcre).`   There may still be LaTeX errors.   To see these you need pdflatex installed with the extra as documented in https://www.swi-prolog.org/build/Debian.txt (bottom) and you need to configure using the cmake option `-DBUILD_PDF_DOCUMENTATION=ON`
  - '$re_portray', etc.  Seems a bug.  On the other hand, why the $?  It is not public anyway.    If you want to keep it as a mostly undocumented feature for development, a private re_portray is just tine.   Developers can use it.   A sensible alternative that we also use in the semweb library is to add a file pcre_portray.pl  that just extends `user:portray`.
  - squash could be too drastic.  We would like to keep the changelog-tagged commits.   Many of the others are too detailed probably.   One option could be to use `git rebase -i master`, so you can reorder and squash sequences of commits.  Squashing sequences is trivial, reordering can be simple, but can also lead to lots of merge conflicts that make it really hard.    If rewriting he changes cleanly is too much work and just squasing sub-sequences doesn't clean it up enough we have to choose between a fulls squash or keep the (history) mess.   It depends.   Notably if commits (too) often rewrite earlier commits the value of a full history is (too) limited IMO.
  
Small PlDOc thing: we try to move as much as possible to markdown in favor of rules derived from older wiki systems.   That means, use `` `foo` `` is preferred over the old proprietary `=foo=`.   A simple replace should do most.  PlDoc's conventions take a single `` ` `` to be syntactically correct Prolog content and a double backquote to be "other" code.  (In markdown they are the same).

On a quick scan all looks great!

**Comment by kamahen** [comment]
After I make the changes you've suggested to the documentation comments, I'll do a `git rebase -i` and squash some of the adjacent commits. Then a `git push --force` -- this should be safe because nobody else has done anything on this branch.

(I have a separate branch with PCRE2 changes that has merged changes from this PR's branch; it'll get messed up by the `git push --force`, but I can deal with that by squashing all its changes into a single commit, something I was planning on doing anyway.)

**Comment by kamahen** [comment]
That should be the last commit.
I'd prefer that you review this PR with the current set of commits; when you're done, I'll do a `git rebase -i` to reduce the number of commits. -- This is because I already have some PCRE2 code and it's easier to merge any changes (without dealing with things like `reflog`)

**Comment by JanWielemaker** [comment]
Thanks!   Hope to find time soon.   Busy today ...

**Comment by kamahen** [comment]
No rush; the bits won't rot. I took way too long to complete this (with some long breaks), so it's only fair that you take whatever time you need. I presume that if you make some small changes to the code, I can git them by "git pull".

**Comment by JanWielemaker** [comment]
All runs fine and my remarks and changes so far are minor.  Then I ran @wouterbeek's SPARQL test suite to encounter this change:

     re_replace("\\Q\\\\E"/g, \\, "a\\b\\c", X).

replacing a single `\` with a double `\\`.   The result however is ``X = "a\\b\\c"``, i.e., no replacement happens.

**Comment by kamahen** [comment]
Where is the SPARQL test suite? I ran all the SWI-Prolog tests and they passed, so do I need to set some additional flags to get more tests?

**Comment by JanWielemaker** [comment]
This suite is not public software.   The re_replace/4 call however returns different results in the old and new version and I think the old version is right.   I'm now investigating the other issue.  Looks like the new version is right here (not yet sure).  Sorry, didn't mean to close ....

**Comment by kamahen** [comment]
The old version didn't properly handle double-backslash (that is, escaped backslashes). It's possible that the new code doesn't do this properly either. ;)
Any test with backslashes ought to be repeated with dollar signs (I haven't done this for all of them).
You might want to inspect the code for string_escape//1 in pcre.pl, and also how it's used.

**Comment by JanWielemaker** [comment]
I think you are right.   A replacement string `\\` is in fact just a single `\`, so this replaces a single `\` with a single `\`.   I guess a quoted replace should also quote the replacement pattern.

**Comment by kamahen** [comment]
A pity that Prolog doesn't have "raw strings" like Python (which seem to be primarily used to make regexps more readable).

I forgot to open an issue for the old code not escaping backslash or dollarsign. But I think I've fixed Issue #1, Issue #2, Issue #3, Issue #4, Issue #5 (I suppose I should close them now - I didn't mark them in the commits).

**Comment by kamahen** [comment]
It occurs to me that there aren't proper tests for things like "\n" (or "\\n") ... any thoughts on these? I presume that PCRE treats "\\n" (that is: a single "\" followed by "n") the same as "\n" (that is: newline) and something similar ought to be done with the `With` string? If so, I suggest opening an Issue for this and I take care of it after the migration to PCRE2.

**Comment by JanWielemaker** [comment]
> A pity that Prolog doesn't have "raw strings" like Python (which seem to be primarily used to make regexps more readable).

We could use quasi quotations.   Actually, it makes some sense, e.g. ``{|re||a\b|}`` and there is the famous char_escapes flag.   We could also extend the syntax, allowing for e.g., R"a\b".  As a variable cannot be an operator, nor can a string, this is always illegal syntax in ISO Prolog.

**Comment by kamahen** [comment]
I've created Issue #10, for handling escape characters.
But I wonder how much work should be put into it, especially as there's the `char_escapes` flag -- which should probably be mentioned in the pcre.pl documentation.

**Comment by JanWielemaker** [comment]
> But I wonder how much work should be put into it, especially as there's the `char_escapes` flag -- which should probably be mentioned in the pcre.pl documentation.

It is more something to keep in mind.   I don't think I'm a big of promoting the `char_escapes` flag.  It was there because ISO wanted character escapes and many Prolog systems didn't have them.   Playing around with this flag is usually asking for trouble.    For long and complicated regular expressions quasi quotations are an option.  We already have the `string`  quasi quotation.  Making a dedicated one for regex would improve things (we can put the options in the re term, e.g.

     {|re([caseless(true)])||aap|}

No hurry.    There are surely people using regular expression in Prolog for small hard coded transformations on strings.   Prolog can do that pretty much ok with DCGs as well though.   The main reason for adding the library was to be able to implement specifications that require (some form of) full regex support like SPARQL, XPATH, etc.

**Comment by JanWielemaker** [comment]
Hi Peter,  I've pushed some minor cleanup to this branch.   See commit comments.  I think I'm happy with it.   There is one thing I spotted in the C code: re_error() performs an assert(0) for a lot of errors where I'm not sure we'd like to terminate the process if they happen.   Things like PCRE_ERROR_NOSUBSTRING can probably be caused by illegal input?  The various limits should definitely go to Prolog resource errors.   It should not be possible to abort the process by making invalid calls to the Prolog library.    A last resort could be to throw error(pcre_error(Code), _) rather than assert(0).

If you do a `rebase -i` I'll merge this into master.

**Comment by kamahen** [comment]
The change to tabling looks good; I'm going to try a few more benchmarks first (including the old assertz) to verify.

As for the predicate options -- I'll review all the options in pcre4pl.c to ensure they match pcreapi.h and then update pcre.pl accordingly.
Is there a way to specify multiple predicates with the same options? And a way of specifying that the options are passed to two predicats -- e.g., re_matchsub passes options to both re_compile and re_matchsub_ ... and is it OK to specify the options to a predicate that isn't exported?

**Comment by JanWielemaker** [comment]
> The change to tabling looks good; I'm going to try a few more benchmarks first (including the old assertz) to verify.

I wouldn't bother too much.   As is, seems to be a small but acceptable performance degradation.   At some point we may look for a more performant approach using goal_expansion/2.    No nee to hurry.

> Is there a way to specify multiple predicates with the same options?

You can only fake by claiming the one passes the options to the other.  See https://www.swi-prolog.org/pldoc/doc_for?object=predicate_options/3

> and is it OK to specify the options to a predicate that isn't exported?

I guess so, but I do not see much reason.   It is also rather rare to use the option interface purely internally in a module.   The main reason is to drive the built-in syntax highlighting that verifies the option is known and performs type checking on the option value.

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/quasi-quotation-api-extension/5060/2

**Comment by kamahen** [comment]
@JanWielemaker - I've done a `rebase -i` on the commits (it was too complicated to reorder some of them, so I just squashed some adjacent commits).
It's ready for you to merge into the master. (And I can get back to working on the PCRE2 changes)

**Comment by JanWielemaker** [comment]
Thanks!   Ready for pcre2 :smile:

**Pull request merged**
